### ISSUE TITLE
Ts === Javascript

### ISSUE THREAD

**Issue by StarpTech** [nats-io/ts-nats#15]
Typescript is always transpiled to Javascript. Why do you make a gap between TS and JS? I thought that the new driver will be released as node-nats@2.0.0.

**Comment by aricart** [comment]
Hi Dustin, we usually name our clients by the language or technology that they are written in.

**Comment by StarpTech** [comment]
so we can expect a coffeescript-nats soon? 😄

**Comment by StarpTech** [comment]
But seriously, do you want to maintain 2 clients in the same technology (javascript) with two separate definition files? or do you plan to mark node-nats as deprecated in the future?

**Comment by aricart** [comment]
Likely node-nats will become a compatibility API wrapper. Not yet decided, but that is the general idea.

**Comment by StarpTech** [comment]
ok, thanks!

**Comment by aricart** [comment]
Still ironing out some details on the ts-client for performance before it is released.

**Comment by StarpTech** [comment]
`ts-node` is now a complete rewrite of `node-nats` how should the community decide which driver is the correct one?
