### ISSUE TITLE
Connect with username and password in the url not working

### ISSUE THREAD

**Issue by deini** [nats-io/ts-nats#24]
Looks like using username and password in the url isn't working:

```ts
// Connect with username and password in the url
let nc6 = await connect({url: 'nats://me:secret@127.0.0.1:4222'});
```

Crashes with `AUTHORIZATION_VIOLATION`, however, using same credentials but passing them as `user` and `pass` does work.

**Comment by aricart** [comment]
I cannot reproduce the issue, I added a test to verify it is working correctly.

**Comment by mlaggner** [comment]
some problem here..
maybe you can reproduce it with the following nats url:

`nats://public:thenewalbiondata@www.albion-online-data.com:4222`
