### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by ramlez** [nats-io/ts-nats#40]
Hello, 

my apologies for a silly question but can I set the connection timeout during connection to NATS server? I haven't found any option for it in `NatsConnectionOptions`.

In NATS [documentation ](https://nats.io/documentation/writing_applications/connecting/?lang=ts) I've found that connection timeout is not supported in nats-ts. But I don't understand the reason why?
![obraz](https://user-images.githubusercontent.com/20826818/54687036-eda8b400-4b1a-11e9-8c5b-03e0f2183f05.png)

Thanks in advance

**Comment by aricart** [comment]
@ramlez, in this case, there's no reason except to say that the node-nats client didn't sport this, so somehow it was missed. Let's fix that.

**Comment by ramlez** [comment]
@aricart thank you for your quick answer and many thanks for "fixing" it! 👍

**Comment by aricart** [comment]
@ramlez - I am going to have to change the option name here to prevent a future collision (node-nats-streaming uses `connectionTimeout`). I am going to rename it to `timeout`.
